import Providers from '@/components/Providers'
import '../globals.scss'

export const metadata = {
	title: 'Login',
	description: 'Generated by Next.js'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
